In [184]:
import pandas as pd
import numpy as np
import re

In [185]:
unemployment20 = pd.read_csv("data/2020_unemployment_barca.csv", sep = ",")
unemployment19 = pd.read_csv("data/2019_unemployment_barca.csv", sep = ",")
unemployment18 = pd.read_csv("data/2018_unemployment_barca.csv", sep = ",")
gender_age = pd.read_csv("data/2020_gender_age.csv", sep=",")

In [186]:
y20q10 = unemployment20[(unemployment20["Mes"]==1) |(unemployment20["Mes"]==2) | (unemployment20["Mes"]==3)]
y20q20 = unemployment20[(unemployment20["Mes"]==4) |(unemployment20["Mes"]==5) | (unemployment20["Mes"]==6)]
y20q30 = unemployment20[(unemployment20["Mes"]==7) |(unemployment20["Mes"]==8) | (unemployment20["Mes"]==9)]
y19q10 = unemployment19[(unemployment19["Mes"]==1) |(unemployment19["Mes"]==2) | (unemployment19["Mes"]==3)]
y19q20 = unemployment19[(unemployment19["Mes"]==4) |(unemployment19["Mes"]==5) | (unemployment19["Mes"]==6)]
y19q30 = unemployment19[(unemployment19["Mes"]==7) |(unemployment19["Mes"]==8) | (unemployment19["Mes"]==9)]
y19q40 = unemployment19[(unemployment19["Mes"]==10) |(unemployment19["Mes"]==11) | (unemployment19["Mes"]==12)]
y18q10 = unemployment18[(unemployment18["Mes"]==1) |(unemployment18["Mes"]==2) | (unemployment18["Mes"]==3)]
y18q20 = unemployment18[(unemployment18["Mes"]==4) |(unemployment18["Mes"]==5) | (unemployment18["Mes"]==6)]
y18q30 = unemployment18[(unemployment18["Mes"]==7) |(unemployment18["Mes"]==8) | (unemployment18["Mes"]==9)]
y18q40 = unemployment18[(unemployment18["Mes"]==10) |(unemployment18["Mes"]==11) | (unemployment18["Mes"]==12)]

y20q1 = pd.DataFrame(y20q10.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y20q2 = pd.DataFrame(y20q20.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y20q3 = pd.DataFrame(y20q30.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y19q1 = pd.DataFrame(y19q10.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y19q2 = pd.DataFrame(y19q20.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y19q3 = pd.DataFrame(y19q30.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y19q4 = pd.DataFrame(y19q40.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y18q1 = pd.DataFrame(y18q10.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y18q2 = pd.DataFrame(y18q20.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y18q3 = pd.DataFrame(y18q30.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())
y18q4 = pd.DataFrame(y18q40.groupby(["Codi_Districte", "Nom_Districte"])["Nombre"].sum())

y20q1["increase"] = (y20q1["Nombre"] / y19q4["Nombre"])-1
y20q2["increase"] = (y20q2["Nombre"] / y20q1["Nombre"])-1
y20q3["increase"] = (y20q3["Nombre"] / y20q2["Nombre"])-1
y19q1["increase"] = (y19q1["Nombre"] / y18q4["Nombre"])-1
y19q2["increase"] = (y19q2["Nombre"] / y19q1["Nombre"])-1
y19q3["increase"] = (y19q3["Nombre"] / y19q2["Nombre"])-1
y19q4["increase"] = (y19q4["Nombre"] / y19q3["Nombre"])-1

y18q2["increase"] = (y18q2["Nombre"] / y18q1["Nombre"])-1
y18q3["increase"] = (y18q3["Nombre"] / y18q2["Nombre"])-1
y18q4["increase"] = (y18q4["Nombre"] / y18q3["Nombre"])-1

y18q1[["Y18_Q2", "Change1"]] = y18q2
y18q1[["Y18_Q3", "Change2"]] = y18q3
y18q1[["Y18_Q4", "Change3"]] = y18q4
y18q1[["Y19_Q1", "Change4"]] = y19q1
y18q1[["Y19_Q2", "Change5"]] = y19q2
y18q1[["Y19_Q3", "Change6"]] = y19q3
y18q1[["Y19_Q4", "Change7"]] = y19q4
y18q1[["Y20_Q1", "Change8"]] = y20q1
y18q1[["Y20_Q2", "Change9"]] = y20q2
y18q1[["Y20_Q3", "Change10"]] = y20q3

full_table = y18q1
full_table.drop(99 , axis = 0, inplace = True)
full_table.rename(columns={"Nombre":"Y18_Q1"}, inplace = True)

total_numbers = full_table[['Y18_Q1', 'Y18_Q2', 'Y18_Q3', 'Y18_Q4', 'Y19_Q1',
                            'Y19_Q2', 'Y19_Q3', 'Y19_Q4', 'Y20_Q1', 'Y20_Q2', 'Y20_Q3']]

total_change = full_table[['Change1', 'Change2', 'Change3', 'Change4','Change5', 'Change6',
                           'Change7', 'Change8', 'Change9', 'Change10']]

total_change.columns = ['Change_Y18Q1', 'Change_Y18Q2', 'Change_y18Q3', 'Change_Y18Q4', 'Change_Y19Q1', 'Change_Y19Q2',
       'Change_Y19Q3', 'Change_Y19Q4', 'Change_Y20Q1', 'Change_Y20Q2']

In [187]:
full_table

,,Y18_Q1,Y18_Q2,Change1,Y18_Q3,Change2,Y18_Q4,Change3,Y19_Q1,Change4,Y19_Q2,...,Y19_Q3,Change6,Y19_Q4,Change7,Y20_Q1,Change8,Y20_Q2,Change9,Y20_Q3,Change10
Codi_Districte,Nom_Districte,,,,,,,,,,,,,,,,,,,,,
1,Ciutat Vella,26034,24220,-0.069678,23564,-0.027085,24642,0.045748,24985,0.013919,23293,...,23009,-0.012193,23806,0.034639,24896,0.045787,61937,1.487829,69816,0.127210
2,Eixample,38125,35843,-0.059856,36246,0.011243,35832,-0.011422,36424,0.016522,34862,...,35673,0.023263,35937,0.007401,36988,0.029246,85889,1.322077,99632,0.160009
3,Sants-Montju√Øc,34022,32365,-0.048704,32386,0.000649,32168,-0.006731,32449,0.008735,31034,...,31356,0.010376,31383,0.000861,32286,0.028774,73364,1.272316,84778,0.155580
4,Les Corts,10982,10516,-0.042433,10756,0.022822,10669,-0.008089,10618,-0.004780,10226,...,10389,0.015940,10465,0.007315,10640,0.016722,24275,1.281485,28129,0.158764
5,Sarri√†-Sant Gervasi,13240,12601,-0.048263,12954,0.028014,12903,-0.003937,12870,-0.002558,12418,...,12988,0.045901,13043,0.004235,13124,0.006210,29835,1.273316,35069,0.175432
6,Gr√†cia,18412,17422,-0.053769,17829,0.023361,17367,-0.025913,17438,0.004088,16851,...,17674,0.048840,17862,0.010637,18294,0.024185,41613,1.274680,48098,0.155841
7,Horta-Guinard√≥,30063,28465,-0.053155,29375,0.031969,28481,-0.030434,28510,0.001018,27647,...,28709,0.038413,28654,-0.001916,29420,0.026733,65124,1.213596,75007,0.151757
8,Nou Barris,37878,36286,-0.042030,35947,-0.009342,35434,-0.014271,35962,0.014901,35074,...,35284,0.005987,35477,0.005470,36508,0.029061,75384,1.064862,86879,0.152486
9,Sant Andreu,28189,27087,-0.039093,27269,0.006719,26575,-0.025450,26698,0.004628,26208,...,26966,0.028922,26594,-0.013795,27675,0.040648,58856,1.126685,67784,0.151692
10,Sant Mart√≠,44166,42077,-0.047299,42758,0.016185,41625,-0.026498,41706,0.001946,40298,...,41609,0.032533,41207,-0.009661,43116,0.046327,91745,1.127864,105761,0.152771

In [188]:
total_numbers

,,Y18_Q1,Y18_Q2,Y18_Q3,Y18_Q4,Y19_Q1,Y19_Q2,Y19_Q3,Y19_Q4,Y20_Q1,Y20_Q2,Y20_Q3
Codi_Districte,Nom_Districte,,,,,,,,,,,
1,Ciutat Vella,26034,24220,23564,24642,24985,23293,23009,23806,24896,61937,69816
2,Eixample,38125,35843,36246,35832,36424,34862,35673,35937,36988,85889,99632
3,Sants-Montju√Øc,34022,32365,32386,32168,32449,31034,31356,31383,32286,73364,84778
4,Les Corts,10982,10516,10756,10669,10618,10226,10389,10465,10640,24275,28129
5,Sarri√†-Sant Gervasi,13240,12601,12954,12903,12870,12418,12988,13043,13124,29835,35069
6,Gr√†cia,18412,17422,17829,17367,17438,16851,17674,17862,18294,41613,48098
7,Horta-Guinard√≥,30063,28465,29375,28481,28510,27647,28709,28654,29420,65124,75007
8,Nou Barris,37878,36286,35947,35434,35962,35074,35284,35477,36508,75384,86879
9,Sant Andreu,28189,27087,27269,26575,26698,26208,26966,26594,27675,58856,67784
10,Sant Mart√≠,44166,42077,42758,41625,41706,40298,41609,41207,43116,91745,105761

In [189]:
total_numbers.describe()

,Y18_Q1,Y18_Q2,Y18_Q3,Y18_Q4,Y19_Q1,Y19_Q2,Y19_Q3,Y19_Q4,Y20_Q1,Y20_Q2,Y20_Q3
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.00000,10.000000
mean,28111.100000,26688.200000,26908.400000,26569.600000,26766.000000,25791.100000,26365.700000,26442.80000,27294.700000,60802.20000,70095.300000
std,11081.153324,10542.133147,10570.193704,10295.839485,10437.272387,10095.586554,10275.675139,10189.77496,10665.037543,22711.75601,26126.128293
min,10982.000000,10516.000000,10756.000000,10669.000000,10618.000000,10226.000000,10389.000000,10465.00000,10640.000000,24275.00000,28129.000000
25%,20317.500000,19121.500000,19262.750000,19185.750000,19324.750000,18461.500000,19007.750000,19348.00000,19944.500000,45923.75000,53019.500000
50%,29126.000000,27776.000000,28322.000000,27528.000000,27604.000000,26927.500000,27837.500000,27624.00000,28547.500000,63530.50000,72411.500000
75%,36914.000000,34973.500000,35056.750000,34617.500000,35083.750000,33905.000000,34302.000000,34453.50000,35452.500000,74879.00000,86353.750000
max,44166.000000,42077.000000,42758.000000,41625.000000,41706.000000,40298.000000,41609.000000,41207.00000,43116.000000,91745.00000,105761.000000

In [190]:
total_change

,,Change_Y18Q1,Change_Y18Q2,Change_y18Q3,Change_Y18Q4,Change_Y19Q1,Change_Y19Q2,Change_Y19Q3,Change_Y19Q4,Change_Y20Q1,Change_Y20Q2
Codi_Districte,Nom_Districte,,,,,,,,,,
1,Ciutat Vella,-0.069678,-0.027085,0.045748,0.013919,-0.067721,-0.012193,0.034639,0.045787,1.487829,0.127210
2,Eixample,-0.059856,0.011243,-0.011422,0.016522,-0.042884,0.023263,0.007401,0.029246,1.322077,0.160009
3,Sants-Montju√Øc,-0.048704,0.000649,-0.006731,0.008735,-0.043607,0.010376,0.000861,0.028774,1.272316,0.155580
4,Les Corts,-0.042433,0.022822,-0.008089,-0.004780,-0.036918,0.015940,0.007315,0.016722,1.281485,0.158764
5,Sarri√†-Sant Gervasi,-0.048263,0.028014,-0.003937,-0.002558,-0.035120,0.045901,0.004235,0.006210,1.273316,0.175432
6,Gr√†cia,-0.053769,0.023361,-0.025913,0.004088,-0.033662,0.048840,0.010637,0.024185,1.274680,0.155841
7,Horta-Guinard√≥,-0.053155,0.031969,-0.030434,0.001018,-0.030270,0.038413,-0.001916,0.026733,1.213596,0.151757
8,Nou Barris,-0.042030,-0.009342,-0.014271,0.014901,-0.024693,0.005987,0.005470,0.029061,1.064862,0.152486
9,Sant Andreu,-0.039093,0.006719,-0.025450,0.004628,-0.018353,0.028922,-0.013795,0.040648,1.126685,0.151692
10,Sant Mart√≠,-0.047299,0.016185,-0.026498,0.001946,-0.033760,0.032533,-0.009661,0.046327,1.127864,0.152771

In [191]:
total_change.describe()

,Change_Y18Q1,Change_Y18Q2,Change_y18Q3,Change_Y18Q4,Change_Y19Q1,Change_Y19Q2,Change_Y19Q3,Change_Y19Q4,Change_Y20Q1,Change_Y20Q2
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,-0.050428,0.010453,-0.010700,0.005842,-0.036699,0.023798,0.004519,0.029369,1.244471,0.154154
std,0.009180,0.018365,0.022000,0.007425,0.013295,0.019109,0.013136,0.012538,0.120101,0.011812
min,-0.069678,-0.027085,-0.030434,-0.004780,-0.067721,-0.012193,-0.013795,0.006210,1.064862,0.127210
25%,-0.053616,0.002166,-0.025797,0.001250,-0.041392,0.011767,-0.001222,0.024822,1.149297,0.151939
50%,-0.048483,0.013714,-0.012846,0.004358,-0.034440,0.026093,0.004852,0.028917,1.272816,0.154176
75%,-0.043650,0.023227,-0.007071,0.012623,-0.031118,0.036943,0.007379,0.037798,1.279784,0.158033
max,-0.039093,0.031969,0.045748,0.016522,-0.018353,0.048840,0.034639,0.046327,1.487829,0.175432

In [192]:
gender_col = ['year', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'gender', 'age', 'Nombre']
gender_age.columns = gender_col

In [193]:
gender_age["age"] = gender_age["age"].str.replace(r"\s.*anys", "")
gender_age["age"] = gender_age["age"].str.replace(r"\s.*i m√©s", "")
gender_age["age"] = gender_age["age"].str.replace(r"\s.*any", "")
gender_age["age"] = gender_age["age"].str.replace(r"^0", "1")

gender_age["age"] = pd.to_numeric(gender_age["age"], errors="coerce")
gender_age["Nombre"] = pd.to_numeric(gender_age["Nombre"], errors="coerce")
gender_age["age_product"] = gender_age["age"] * gender_age["Nombre"]

x = pd.DataFrame(gender_age.groupby(["Nom_Districte"])["age_product"].sum())
age = pd.DataFrame(gender_age.groupby(["Nom_Districte"])["Nombre"].sum())
age["avg_age"] = x["age_product"] / age["Nombre"]
age.columns = ["Population", "AVG Age"]

In [194]:
age = age.sort_values(by = "Population", ascending = False)
age

                     Population    AVG Age
Nom_Districte
Eixample                 270694  44.581642
Sant Mart√≠               241691  43.667406
Sants-Montju√Øc           187584  43.697373
Horta-Guinard√≥           174799  45.089629
Nou Barris               174012  44.291790
Sant Andreu              151976  44.211718
Sarri√†-Sant Gervasi      151157  43.079844
Gr√†cia                   123651  44.055770
Ciutat Vella             108331  39.336100
Les Corts                 82635  45.814183

In [195]:
total_numbers["Y20_Q3"] / age["Population"]

Codi_Districte  Nom_Districte
1               Ciutat Vella           0.644469
2               Eixample               0.368061
3               Sants-Montju√Øc         0.451947
4               Les Corts              0.340401
5               Sarri√†-Sant Gervasi    0.232004
6               Gr√†cia                 0.388982
7               Horta-Guinard√≥         0.429104
8               Nou Barris             0.499270
9               Sant Andreu            0.446018
10              Sant Mart√≠             0.437588
dtype: float64